import torch


VAE_LATENT_SCALE = 0.18215


def uses_siglip_image_encoder(model):

    return (
        getattr(
            model.params,
            "image_encoder_arch",
            "cnn"
        )
        == "siglip"
    )


def get_reconstruction_targets(model, x):

    if not uses_siglip_image_encoder(model):
        return x

    # x[0] is now RGB
    rgb = x[0]

    vae = model.pretrained_vae
    vae_device = next(
        vae.parameters()
    ).device

    rgb = (
        rgb.to(vae_device)
        .float()
        .mul(2)
        .sub(1)
    )

    # Target only -> gradients unnecessary.
    with torch.no_grad():

        image_target = (
            vae
            .encode(rgb)
            .latent_dist
            .sample()
            * VAE_LATENT_SCALE
        )

    targets = list(x)

    # Replace ONLY image reconstruction target.
    targets[0] = image_target

    return targets


def prepare_augmented_data_for_encoder(
    model,
    aug_data,
    view_index,
):

    # Text modality or original CNN:
    # nothing changes.
    if (
        view_index != 0
        or not uses_siglip_image_encoder(model)
    ):
        return aug_data

    # aug_data is generated by the OLD image decoder,
    # so it is [B,4,32,32].
    vae = model.pretrained_vae

    vae_device = next(
        vae.parameters()
    ).device

    latent = aug_data.to(vae_device)

    # IMPORTANT: no torch.no_grad() here.
    #
    # VAE parameters are frozen, but gradients must pass
    # from SigLIP -> VAE decoder -> IDMVAE decoder.
    rgb = vae.decode(
        latent / VAE_LATENT_SCALE
    ).sample

    rgb = (
        rgb
        .add(1)
        .div(2)
        .clamp(0, 1)
    )

    return rgb